### ISSUE TITLE
runtime error with go 1.14.2

### ISSUE THREAD

**Issue by predmond** [flier/gohs#20] opened 2020-05-12 15:01 UTC
I'm trying to update my code to use go 1.14.2.  When I run my tests for code using gohs I'm getting a runtime error:

Any idea what could cause this?

```
runtime: pointer 0xc000433860 to unallocated span span.base()=0xc00042c000 span.limit=0xc000434000 span.state=0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

goroutine 76 [running, locked to thread]:
runtime.throw(0x20b2be3, 0x3e)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00090d3a0 sp=0xc00090d370 pc=0x44cb52
runtime.badPointer(0x7fccb647c2b0, 0xc000433860, 0x0, 0x0)
	/usr/local/go/src/runtime/mbitmap.go:380 +0x230 fp=0xc00090d3e8 sp=0xc00090d3a0 pc=0x42cae0
runtime.findObject(0xc000433860, 0x0, 0x0, 0x1000, 0xc000040300, 0x14)
	/usr/local/go/src/runtime/mbitmap.go:416 +0x9b fp=0xc00090d420 sp=0xc00090d3e8 pc=0x42cb8b
runtime.checkptrBase(0xc000433860, 0xc0003fdf94)
	/usr/local/go/src/runtime/checkptr.go:68 +0x4f fp=0xc00090d460 sp=0xc00090d420 pc=0x41e07f
runtime.checkptrAlignment(0xc000433860, 0x1ee6bc0, 0x1)
	/usr/local/go/src/runtime/checkptr.go:19 +0x75 fp=0xc00090d490 sp=0xc00090d460 pc=0x41ded5
github.com/flier/gohs/hyperscan.hsMatchEventCallback(0x1, 0x0, 0x8, 0x3ff1f7c100000000, 0xc000433860, 0x32668b4)
	/swarm/gopath/pkg/mod/github.com/flier/gohs@v1.0.0/hyperscan/internal.go:910 +0x52 fp=0xc00090d4e8 sp=0xc00090d490 pc=0x19a22a2
github.com/flier/gohs/hyperscan._cgoexpwrap_16a4143cf05d_hsMatchEventCallback(0x1, 0x0, 0x8, 0x7fcc00000000, 0xc000433860, 0x7fcceaa51534)
	_cgo_gotypes.go:946 +0x5d fp=0xc00090d530 sp=0xc00090d4e8 pc=0x199f50d
runtime.call64(0x0, 0x7ffc0bf6b970, 0x7ffc0bf6ba00, 0x30)
	/usr/local/go/src/runtime/asm_amd64.s:540 +0x3b fp=0xc00090d580 sp=0xc00090d530 pc=0x47fc0b
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:332 +0x1ac fp=0xc00090d618 sp=0xc00090d580 pc=0x41a77c
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:207 +0xc1 fp=0xc00090d680 sp=0xc00090d618 pc=0x41a531
runtime.cgocallback_gofunc(0x41a3de, 0x1ce4eb0, 0xc00090d710, 0xc00090d700)
	/usr/local/go/src/runtime/asm_amd64.s:793 +0x9b fp=0xc00090d6a0 sp=0xc00090d680 pc=0x48115b
runtime.asmcgocall(0x1ce4eb0, 0xc00090d710)
	/usr/local/go/src/runtime/asm_amd64.s:640 +0x42 fp=0xc00090d6a8 sp=0xc00090d6a0 pc=0x480ff2
runtime.cgocall(0x1ce4eb0, 0xc00090d710, 0xc0003fdfe8)
	/usr/local/go/src/runtime/cgocall.go:143 +0x9e fp=0xc00090d6e0 sp=0xc00090d6a8 pc=0x41a3de
github.com/flier/gohs/hyperscan._Cfunc_hs_scan_vector_cgo(0x6107dc0, 0xc0003fdfe8, 0xc00042a000, 0x1, 0x6153dc0, 0xc000433860, 0x0)
	_cgo_gotypes.go:662 +0x6b fp=0xc00090d710 sp=0xc00090d6e0 pc=0x199e96b
github.com/flier/gohs/hyperscan.hsScanVector.func1(0x6107dc0, 0xc000433800, 0xc00042a000, 0x1, 0x1, 0xc000739160, 0x1, 0x1, 0x0, 0x6153dc0, ...)
	/swarm/gopath/pkg/mod/github.com/flier/gohs@v1.0.0/hyperscan/internal.go:959 +0x1a4 fp=0xc00090d770 sp=0xc00090d710 pc=0x19a4934
github.com/flier/gohs/hyperscan.hsScanVector(0x6107dc0, 0xc000739160, 0x1, 0x1, 0x0, 0x6153dc0, 0xc0003df0f0, 0x0, 0x0, 0x10000c000433940, ...)
	/swarm/gopath/pkg/mod/github.com/flier/gohs@v1.0.0/hyperscan/internal.go:959 +0x24b fp=0xc00090d888 sp=0xc00090d770 pc=0x19a273b
github.com/flier/gohs/hyperscan.(*vectoredScanner).Scan(0xc000633c48, 0xc000739160, 0x1, 0x1, 0xc000633c68, 0xc0003df0f0, 0x0, 0x0, 0x0, 0x0)
	/swarm/gopath/pkg/mod/github.com/flier/gohs@v1.0.0/hyperscan/runtime.go:276 +0x133 fp=0xc00090d960 sp=0xc00090d888 pc=0x1999013
github.com/flier/gohs/hyperscan.(*vectoredDatabase).Scan(0xc000633c58, 0xc000739160, 0x1, 0x1, 0xc000633c68, 0xc0003df0f0, 0x0, 0x0, 0xc000433ac0, 0x7ae51a)
```

**Comment by flier** [comment] 2020-05-22 03:21
Very strange, I updated the third-party library and the problem is not reproduced, can you try again?

**Comment by flier** [comment] 2020-06-08 07:58
@predmond If there is no other feedback I will close this issue.

**Closed** 2021-03-21 07:01 UTC
